ALTER TABLE User MODIFY UserAuthenticationStatus INT(2) NOT NULL DEFAULT 0;
ALTER TABLE User MODIFY UserGroupId INT(2) NOT NULL DEFAULT 0; 
ALTER TABLE User MODIFY UserGender INT(1) NOT NULL DEFAULT 0;
ALTER TABLE User MODIFY UserEmail varchar(32) NOT NULL UNIQUE;