ALTER TABLE Activity MODIFY ActivityBeginDate TIMESTAMP NOT NULL DEFAULT 0;
ALTER TABLE Activity MODIFY ActivityEndDate TIMESTAMP NOT NULL DEFAULT 0; 
ALTER TABLE Activity MODIFY ActivityCapacity INT(32) NOT NULL DEFAULT 0;