#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

mysqldump -uroot -d hongkongresort activity > $basedir/create_table_activity.sql
mysqldump -uroot -d hongkongresort assessment > $basedir/create_table_assessment.sql
mysqldump -uroot -d hongkongresort comment > $basedir/create_table_comment.sql
mysqldump -uroot -d hongkongresort image > $basedir/create_table_image.sql
mysqldump -uroot -d hongkongresort login > $basedir/create_table_login.sql
mysqldump -uroot -d hongkongresort notification > $basedir/create_table_notification.sql 
mysqldump -uroot -d hongkongresort player_activity_relation > $basedir/create_table_player_activity_relation.sql
mysqldump -uroot -d hongkongresort player > $basedir/create_table_player.sql
mysqldump -uroot -d hongkongresort perm_foreign_party > $basedir/create_table_perm_foreign_party.sql
mysqldump -uroot -d hongkongresort temp_foreign_party > $basedir/create_table_temp_foreign_party.sql
 

