#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

host='localhost'
dbname='hongkongresort'
user='root'

mysqldump -u $user -h $host --default-character-set=utf8 $dbname -r $basedir/all_data.sql
