#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

host='localhost'
dbname='hongkongresort'
user='root'
extra_opt='--default-character-set=utf8'

mysqldump -h $host -u $user $extra_opt $dbname player | sed 's/ AUTO_INCREMENT=[0-9]*//g' > $basedir/create_table_player.sql

tables=( activity player_activity_relation login image assessment comment notification temp_foreign_party perm_foreign_party )

for tablename in "${tables[@]}"
do
	mysqldump -h $host -u $user -d $extra_opt $dbname $tablename | sed 's/ AUTO_INCREMENT=[0-9]*//g' > $basedir/create_table_"$tablename".sql
done
