#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

host='localhost'
dbname='hongkongresort'
user='root'

mysql -h $host -u $user $dbname < $basedir/create_table_player.sql
mysql -h $host -u $user $dbname < $basedir/create_table_activity.sql
mysql -h $host -u $user $dbname < $basedir/create_table_image.sql
mysql -h $host -u $user $dbname < $basedir/create_table_comment.sql
mysql -h $host -u $user $dbname < $basedir/create_table_assessment.sql
mysql -h $host -u $user $dbname < $basedir/create_table_login.sql
mysql -h $host -u $user $dbname < $basedir/create_table_notification.sql
mysql -h $host -u $user $dbname < $basedir/create_table_player_activity_relation.sql
mysql -h $host -u $user $dbname < $basedir/create_table_temp_foreign_party.sql
mysql -h $host -u $user $dbname < $basedir/create_table_perm_foreign_party.sql
